//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        public decimal BOOKING_ID { get; set; }
        public decimal CUSTOMER_ID { get; set; }
        public decimal JOURNEY_ID { get; set; }
        public decimal STARTING_STOP { get; set; }
        public decimal ENDING_STOP { get; set; }
        public System.DateTime DATE_TIME { get; set; }
        public decimal PRICE { get; set; }
        public Nullable<decimal> AMOUNT_OF_PEOPLE { get; set; }
        public bool STATUS { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual STATION STATION { get; set; }
        public virtual JOURNEY JOURNEY { get; set; }
        public virtual STATION STATION1 { get; set; }
    }
}
