//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKINGS_HISTORY
    {
        public decimal BOOKING_REFERENCE { get; set; }
        public decimal CUSTOMER_ID { get; set; }
        public decimal JOURNEY_ID { get; set; }
        public decimal DEPARTING_STOP { get; set; }
        public decimal ARRIVAL_STOP { get; set; }
        public System.DateTime BOOKED_DATETIME { get; set; }
        public decimal PASSENGERS_SENIOR { get; set; }
        public decimal PASSENGERS_ADULT { get; set; }
        public decimal PASSENGERS_TEENAGER { get; set; }
        public decimal PASSENGERS_INFANT { get; set; }
        public decimal AMOUNT_PAID { get; set; }
        public decimal AMOUNT_OF_PEOPLE { get; set; }
        public bool STATUS { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
