//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COACHES_ARCHIVE
    {
        public decimal COACH_ID { get; set; }
        public string COACH_MAKE { get; set; }
        public string COACH_MODEL { get; set; }
        public string REGISTRATION_PLATE { get; set; }
        public decimal COACH_CAPACITY { get; set; }
    }
}
