//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COACH()
        {
            this.JOURNEYS = new HashSet<JOURNEY>();
            this.REPLACEMENTS = new HashSet<REPLACEMENT>();
        }
    
        public decimal COACH_ID { get; set; }
        public string COACH_MAKE { get; set; }
        public string COACH_MODEL { get; set; }
        public string REGISTRATION_PLATE { get; set; }
        public decimal COACH_CAPACITY { get; set; }
        public bool IS_ACTIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOURNEY> JOURNEYS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPLACEMENT> REPLACEMENTS { get; set; }
    }
}
