//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using Newtonsoft.Json;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.Serialization;


    //[DataContract]
    public partial class CUSTOMER
    {
        //[DataMember(Name = "customerId")]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [JsonProperty("customerId")]
        public decimal CUSTOMER_ID { get; set; }

        //[DataMember(Name = "firstName")]
        [JsonProperty("firstName")]
        [Required]
        public string FIRST_NAME { get; set; }

        //[DataMember(Name = "lastName")]
        [JsonProperty("lastName")]
        [Required]
        public string LAST_NAME { get; set; }

        //[DataMember(Name = "dateOfBirth")]
        [JsonProperty("dateOfBirth")]
        [Required]
        public System.DateTime DATE_OF_BIRTH { get; set; }

        //[DataMember(Name = "addressLineOne")]
        [JsonProperty("addressLineOne")]
        [Required]
        public string ADDRESS_LINE_1 { get; set; }

        //[DataMember(Name = "addressLineTwo")]
        [JsonProperty("addressLineTwo")]
        public string ADDRESS_LINE_2 { get; set; }

        //[DataMember(Name = "postCode")]
        [JsonProperty("postCode")]
        [Required]
        public string POSTCODE { get; set; }

        //[DataMember(Name = "phoneNumber")]
        [JsonProperty("phoneNumber")]
        [Required]
        public string PHONE_NUMBER { get; set; }

        //[DataMember(Name = "emailAddress")]
        [JsonProperty("emailAddress")]
        [Required]
        public string EMAIL { get; set; }

        [JsonProperty("password")]
        [Required]
        public string PASSWORD { get; set; }
    }
}
