//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.BOOKINGS = new HashSet<BOOKING>();
            this.BOOKINGS_HISTORY = new HashSet<BOOKINGS_HISTORY>();
        }
    
        public decimal CUSTOMER_ID { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string CUSTOMER_HASHED_PASSWORD { get; set; }
        public string PASSWORD_SALT { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public System.DateTime DATE_OF_BIRTH { get; set; }
        public string ADDRESS_LINE_ONE { get; set; }
        public string ADDRESS_LINE_TWO { get; set; }
        public string POSTCODE { get; set; }
        public string MOBILE_NUMBER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING> BOOKINGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKINGS_HISTORY> BOOKINGS_HISTORY { get; set; }
    }
}
