//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOURNEY
    {
        public decimal JOURNEY_ID { get; set; }
        public decimal ROUTE_ID { get; set; }
        public decimal COACH_ID { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public decimal START_STATION { get; set; }
        public decimal END_STATION { get; set; }
        public System.DateTime START_DATE_TIME { get; set; }
        public System.DateTime END_DATE_TIME { get; set; }
    
        public virtual COACH COACH { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual ROUTE ROUTE { get; set; }
        public virtual STATION STATION { get; set; }
        public virtual STATION STATION1 { get; set; }
    }
}
