//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOURNEY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JOURNEY()
        {
            this.BOOKINGS = new HashSet<BOOKING>();
        }
    
        public decimal JOURNEY_ID { get; set; }
        public decimal ROUTE_ID { get; set; }
        public decimal COACH_ID { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public System.DateTime START_DATE_TIME { get; set; }
        public System.DateTime END_DATE_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING> BOOKINGS { get; set; }
        public virtual COACH COACH { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual ROUTE ROUTE { get; set; }
    }
}
