//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPLACEMENT
    {
        public decimal REPLACEMENT_ID { get; set; }
        public decimal JOURNEY_ID { get; set; }
        public decimal COACH_ID { get; set; }
        public System.DateTime REQUESTED_DATETIME { get; set; }
        public Nullable<System.DateTime> COMPLETED_DATETIME { get; set; }
        public string STATUS { get; set; }
    
        public virtual COACH COACH { get; set; }
        public virtual JOURNEY JOURNEY { get; set; }
    }
}
