//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROUTE
    {
        public decimal ROUTE_ID { get; set; }
        public decimal DEPARTURE_STATION { get; set; }
        public decimal ARRIVAL_STATION { get; set; }
    }
}
