//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROUTE_STOPS
    {
        public decimal ROUTE_ID { get; set; }
        public decimal STOP_ID { get; set; }
        public decimal POSITION_IN_ROUTE { get; set; }
    
        public virtual ROUTE ROUTE { get; set; }
        public virtual STOP STOP { get; set; }
    }
}
