//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROUTES_ARCHIVE
    {
        public decimal ROUTE_ID { get; set; }
        public Nullable<decimal> DEPARTURE_STATION { get; set; }
        public Nullable<decimal> ARRIVAL_STATION { get; set; }
    
        public virtual STOP STOP { get; set; }
        public virtual STOP STOP1 { get; set; }
    }
}
