//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRCS252_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public decimal CUSTOMER_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public System.DateTime DATE_OF_BIRTH { get; set; }
        public string ADDRESS_LINE_1 { get; set; }
        public string ADDRESS_LINE_2 { get; set; }
        public string POSTCODE { get; set; }
        public Nullable<decimal> PHONE_NUMBER { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
    }
}
