//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRCS252_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIFT
    {
        public decimal SHIFT_ID { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public string ROUTE_ID { get; set; }
        public decimal COACH_ID { get; set; }
    
        public virtual COACH COACH { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual ROUTE ROUTE { get; set; }
    }
}
