//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES_ARCHIVE
    {
        public string EMPLOYEE_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string JOB_ROLE { get; set; }
    }
}
