--------------------------------------------------------
--  File created - Wednesday-May-01-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COACHES
--------------------------------------------------------

  CREATE TABLE "PRCS251E"."COACHES" 
   (	"COACH_ID" NUMBER, 
	"COACH_MAKE" VARCHAR2(35 BYTE), 
	"COACH_MODEL" VARCHAR2(35 BYTE), 
	"REGISTRATION_PLATE" VARCHAR2(8 BYTE), 
	"COACH_CAPACITY" NUMBER, 
	"IS_AVAILABLE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PRCS251E.COACHES
SET DEFINE OFF;
Insert into PRCS251E.COACHES (COACH_ID,COACH_MAKE,COACH_MODEL,REGISTRATION_PLATE,COACH_CAPACITY,IS_AVAILABLE) values (7,'Skoda Transportation','9Tr','AT15 PFA',150,1);
Insert into PRCS251E.COACHES (COACH_ID,COACH_MAKE,COACH_MODEL,REGISTRATION_PLATE,COACH_CAPACITY,IS_AVAILABLE) values (8,'Skoda Transportation','14Tr','AW16 ORE',50,1);
Insert into PRCS251E.COACHES (COACH_ID,COACH_MAKE,COACH_MODEL,REGISTRATION_PLATE,COACH_CAPACITY,IS_AVAILABLE) values (9,'Volvo','B11R','TU19 PRO',200,1);
Insert into PRCS251E.COACHES (COACH_ID,COACH_MAKE,COACH_MODEL,REGISTRATION_PLATE,COACH_CAPACITY,IS_AVAILABLE) values (10,'Volvo','9900','KF68 LGJ',160,1);
Insert into PRCS251E.COACHES (COACH_ID,COACH_MAKE,COACH_MODEL,REGISTRATION_PLATE,COACH_CAPACITY,IS_AVAILABLE) values (11,'Volvo','B8R','OW79 JEQ',150,0);
Insert into PRCS251E.COACHES (COACH_ID,COACH_MAKE,COACH_MODEL,REGISTRATION_PLATE,COACH_CAPACITY,IS_AVAILABLE) values (12,'Custom Bus','315','LW14 KGA',50,1);
Insert into PRCS251E.COACHES (COACH_ID,COACH_MAKE,COACH_MODEL,REGISTRATION_PLATE,COACH_CAPACITY,IS_AVAILABLE) values (13,'Fiat','470','AM13 AGK',75,0);
Insert into PRCS251E.COACHES (COACH_ID,COACH_MAKE,COACH_MODEL,REGISTRATION_PLATE,COACH_CAPACITY,IS_AVAILABLE) values (14,'Volvo','7900','AJ16 LFA',110,0);
Insert into PRCS251E.COACHES (COACH_ID,COACH_MAKE,COACH_MODEL,REGISTRATION_PLATE,COACH_CAPACITY,IS_AVAILABLE) values (17,'Custom Bus','510','GA67 JGA',55,1);
Insert into PRCS251E.COACHES (COACH_ID,COACH_MAKE,COACH_MODEL,REGISTRATION_PLATE,COACH_CAPACITY,IS_AVAILABLE) values (18,'Hyundai Motor Company','Aero','LA99 JAW',70,1);
Insert into PRCS251E.COACHES (COACH_ID,COACH_MAKE,COACH_MODEL,REGISTRATION_PLATE,COACH_CAPACITY,IS_AVAILABLE) values (19,'Hyundai Motor Company','Aero City','KG01 LAI',50,0);
Insert into PRCS251E.COACHES (COACH_ID,COACH_MAKE,COACH_MODEL,REGISTRATION_PLATE,COACH_CAPACITY,IS_AVAILABLE) values (20,'Volvo','B6','LT79 JEB',80,0);
Insert into PRCS251E.COACHES (COACH_ID,COACH_MAKE,COACH_MODEL,REGISTRATION_PLATE,COACH_CAPACITY,IS_AVAILABLE) values (21,'Plaxton','Centro','JN08 JAN',100,0);
Insert into PRCS251E.COACHES (COACH_ID,COACH_MAKE,COACH_MODEL,REGISTRATION_PLATE,COACH_CAPACITY,IS_AVAILABLE) values (22,'Mercedes-Benz','Cito','BP17 JPA',150,1);
Insert into PRCS251E.COACHES (COACH_ID,COACH_MAKE,COACH_MODEL,REGISTRATION_PLATE,COACH_CAPACITY,IS_AVAILABLE) values (23,'Toyota','Coaster','NA59 AKT',170,1);
Insert into PRCS251E.COACHES (COACH_ID,COACH_MAKE,COACH_MODEL,REGISTRATION_PLATE,COACH_CAPACITY,IS_AVAILABLE) values (24,'Isuzu','Cubic','JG86 LSJ',150,1);
Insert into PRCS251E.COACHES (COACH_ID,COACH_MAKE,COACH_MODEL,REGISTRATION_PLATE,COACH_CAPACITY,IS_AVAILABLE) values (25,'Wrightbus','Eclipse Fusion','OF03 SHW',40,1);
Insert into PRCS251E.COACHES (COACH_ID,COACH_MAKE,COACH_MODEL,REGISTRATION_PLATE,COACH_CAPACITY,IS_AVAILABLE) values (26,'Isuzu','Erga','JG79 MNR',45,1);
Insert into PRCS251E.COACHES (COACH_ID,COACH_MAKE,COACH_MODEL,REGISTRATION_PLATE,COACH_CAPACITY,IS_AVAILABLE) values (27,'Isuzu','Fortuna','KG74 LRN',50,1);
Insert into PRCS251E.COACHES (COACH_ID,COACH_MAKE,COACH_MODEL,REGISTRATION_PLATE,COACH_CAPACITY,IS_AVAILABLE) values (6,'VW','Carriage','VW45 34N',100,1);
--------------------------------------------------------
--  DDL for Index COACHES_COACH_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRCS251E"."COACHES_COACH_ID_PK" ON "PRCS251E"."COACHES" ("COACH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COACHES_REGISTRATION_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRCS251E"."COACHES_REGISTRATION_UN" ON "PRCS251E"."COACHES" ("REGISTRATION_PLATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_ARCHIVE_COACHES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PRCS251E"."TRG_ARCHIVE_COACHES" 
BEFORE DELETE ON coaches FOR EACH ROW
BEGIN
    INSERT INTO coaches_archive
        (coach_id, coach_make, coach_model, registration_plate, coach_capacity)
    VALUES
        (:OLD.coach_id, :OLD.coach_make, :OLD.coach_model, :OLD.registration_plate, 
        :OLD.coach_capacity);
END;
/
ALTER TRIGGER "PRCS251E"."TRG_ARCHIVE_COACHES" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_COACH_INITIALISE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PRCS251E"."TRG_COACH_INITIALISE" 
BEFORE INSERT ON coaches FOR EACH ROW
BEGIN
    SELECT seq_coach_id.nextval
    INTO :NEW.coach_id
    FROM sys.dual;
END;
/
ALTER TRIGGER "PRCS251E"."TRG_COACH_INITIALISE" ENABLE;
--------------------------------------------------------
--  Constraints for Table COACHES
--------------------------------------------------------

  ALTER TABLE "PRCS251E"."COACHES" MODIFY ("COACH_CAPACITY" CONSTRAINT "COACHES_COACH_CAPACITY_NN" NOT NULL ENABLE);
  ALTER TABLE "PRCS251E"."COACHES" ADD CONSTRAINT "COACHES_COACH_ID_PK" PRIMARY KEY ("COACH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRCS251E"."COACHES" MODIFY ("COACH_MAKE" CONSTRAINT "COACHES_COACH_MAKE_NN" NOT NULL ENABLE);
  ALTER TABLE "PRCS251E"."COACHES" MODIFY ("COACH_MODEL" CONSTRAINT "COACHES_COACH_MODEL_NN" NOT NULL ENABLE);
  ALTER TABLE "PRCS251E"."COACHES" MODIFY ("IS_AVAILABLE" CONSTRAINT "COACHES_IS_AVAILABLE_NN" NOT NULL ENABLE);
  ALTER TABLE "PRCS251E"."COACHES" MODIFY ("REGISTRATION_PLATE" CONSTRAINT "COACHES_REGISTRATION_NN" NOT NULL ENABLE);
  ALTER TABLE "PRCS251E"."COACHES" ADD CONSTRAINT "COACHES_REGISTRATION_UN" UNIQUE ("REGISTRATION_PLATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRCS251E"."COACHES" ADD CONSTRAINT "IS_AVAILABLE_CHK" CHECK (is_available IN (0, 1)) ENABLE;
