--------------------------------------------------------
--  File created - Wednesday-May-01-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SHIFTS
--------------------------------------------------------

  CREATE TABLE "PRCS251E"."SHIFTS" 
   (	"SHIFT_ID" NUMBER, 
	"EMPLOYEE_ID" VARCHAR2(15 BYTE), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PRCS251E.SHIFTS
SET DEFINE OFF;
Insert into PRCS251E.SHIFTS (SHIFT_ID,EMPLOYEE_ID,START_DATETIME,END_DATETIME) values (2,'D1006',to_date('27-APR-19','DD-MON-RR'),to_date('27-APR-19','DD-MON-RR'));
Insert into PRCS251E.SHIFTS (SHIFT_ID,EMPLOYEE_ID,START_DATETIME,END_DATETIME) values (3,'D1020',to_date('04-MAY-19','DD-MON-RR'),to_date('04-MAY-19','DD-MON-RR'));
Insert into PRCS251E.SHIFTS (SHIFT_ID,EMPLOYEE_ID,START_DATETIME,END_DATETIME) values (4,'D1020',to_date('05-MAY-19','DD-MON-RR'),to_date('05-MAY-19','DD-MON-RR'));
Insert into PRCS251E.SHIFTS (SHIFT_ID,EMPLOYEE_ID,START_DATETIME,END_DATETIME) values (5,'D1022',to_date('03-MAY-19','DD-MON-RR'),to_date('04-MAY-19','DD-MON-RR'));
Insert into PRCS251E.SHIFTS (SHIFT_ID,EMPLOYEE_ID,START_DATETIME,END_DATETIME) values (6,'D1024',to_date('06-MAY-19','DD-MON-RR'),to_date('06-MAY-19','DD-MON-RR'));
Insert into PRCS251E.SHIFTS (SHIFT_ID,EMPLOYEE_ID,START_DATETIME,END_DATETIME) values (7,'D1024',to_date('08-MAY-19','DD-MON-RR'),to_date('08-MAY-19','DD-MON-RR'));
Insert into PRCS251E.SHIFTS (SHIFT_ID,EMPLOYEE_ID,START_DATETIME,END_DATETIME) values (8,'D1029',to_date('07-MAY-19','DD-MON-RR'),to_date('07-MAY-19','DD-MON-RR'));
Insert into PRCS251E.SHIFTS (SHIFT_ID,EMPLOYEE_ID,START_DATETIME,END_DATETIME) values (9,'D1030',to_date('09-MAY-19','DD-MON-RR'),to_date('09-MAY-19','DD-MON-RR'));
Insert into PRCS251E.SHIFTS (SHIFT_ID,EMPLOYEE_ID,START_DATETIME,END_DATETIME) values (10,'D1036',to_date('09-MAY-19','DD-MON-RR'),to_date('09-MAY-19','DD-MON-RR'));
Insert into PRCS251E.SHIFTS (SHIFT_ID,EMPLOYEE_ID,START_DATETIME,END_DATETIME) values (11,'D1029',to_date('11-MAY-19','DD-MON-RR'),to_date('11-MAY-19','DD-MON-RR'));
Insert into PRCS251E.SHIFTS (SHIFT_ID,EMPLOYEE_ID,START_DATETIME,END_DATETIME) values (12,'D1036',to_date('10-MAY-19','DD-MON-RR'),to_date('11-MAY-19','DD-MON-RR'));
Insert into PRCS251E.SHIFTS (SHIFT_ID,EMPLOYEE_ID,START_DATETIME,END_DATETIME) values (13,'D1038',to_date('10-MAY-19','DD-MON-RR'),to_date('10-MAY-19','DD-MON-RR'));
Insert into PRCS251E.SHIFTS (SHIFT_ID,EMPLOYEE_ID,START_DATETIME,END_DATETIME) values (14,'D1022',to_date('13-MAY-19','DD-MON-RR'),to_date('13-MAY-19','DD-MON-RR'));
Insert into PRCS251E.SHIFTS (SHIFT_ID,EMPLOYEE_ID,START_DATETIME,END_DATETIME) values (15,'D1031',to_date('06-MAY-19','DD-MON-RR'),to_date('06-MAY-19','DD-MON-RR'));
Insert into PRCS251E.SHIFTS (SHIFT_ID,EMPLOYEE_ID,START_DATETIME,END_DATETIME) values (16,'D1036',to_date('12-MAY-19','DD-MON-RR'),to_date('13-MAY-19','DD-MON-RR'));
Insert into PRCS251E.SHIFTS (SHIFT_ID,EMPLOYEE_ID,START_DATETIME,END_DATETIME) values (17,'D1030',to_date('04-MAY-19','DD-MON-RR'),to_date('04-MAY-19','DD-MON-RR'));
Insert into PRCS251E.SHIFTS (SHIFT_ID,EMPLOYEE_ID,START_DATETIME,END_DATETIME) values (18,'D1022',to_date('12-MAY-19','DD-MON-RR'),to_date('12-MAY-19','DD-MON-RR'));
Insert into PRCS251E.SHIFTS (SHIFT_ID,EMPLOYEE_ID,START_DATETIME,END_DATETIME) values (19,'D1006',to_date('02-MAY-19','DD-MON-RR'),to_date('02-MAY-19','DD-MON-RR'));
Insert into PRCS251E.SHIFTS (SHIFT_ID,EMPLOYEE_ID,START_DATETIME,END_DATETIME) values (20,'D1006',to_date('03-MAY-19','DD-MON-RR'),to_date('03-MAY-19','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index SHIFTS_SHIFT_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRCS251E"."SHIFTS_SHIFT_ID_PK" ON "PRCS251E"."SHIFTS" ("SHIFT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_SHIFT_INITIALISE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PRCS251E"."TRG_SHIFT_INITIALISE" 
BEFORE INSERT ON shifts FOR EACH ROW
BEGIN
    SELECT seq_shift_id.nextval
    INTO :NEW.shift_id
    FROM sys.dual;
END;
/
ALTER TRIGGER "PRCS251E"."TRG_SHIFT_INITIALISE" ENABLE;
--------------------------------------------------------
--  Constraints for Table SHIFTS
--------------------------------------------------------

  ALTER TABLE "PRCS251E"."SHIFTS" MODIFY ("END_DATETIME" CONSTRAINT "SHIFTS_END_DATETIME_NN" NOT NULL ENABLE);
  ALTER TABLE "PRCS251E"."SHIFTS" ADD CONSTRAINT "SHIFTS_SHIFT_ID_PK" PRIMARY KEY ("SHIFT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRCS251E"."SHIFTS" MODIFY ("START_DATETIME" CONSTRAINT "SHIFTS_START_DATETIME_NN" NOT NULL ENABLE);
  ALTER TABLE "PRCS251E"."SHIFTS" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
